/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package id.luthfiswees.yaml.manipulator;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class YamlManipulatorTest {
    // @Test void someLibraryMethodReturnsTrue() {
    //     Library classUnderTest = new Library();
    //     assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    // }
}
