# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java Unit Test with Gradle

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Test with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: test

  publish:
    needs: [test]
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Creating Gradle properties file
      shell: bash
      env:
        OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
        OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY_KEYRING_FILE: ${{ secrets.SIGNING_KEY_KEYRING_FILE }}
      run: |
          mkdir -p ~/.gradle/
          echo $SIGNING_KEY_KEYRING_FILE | base64 --decode > ~/secring.kbx
          echo "signing.keyId=${SIGNING_KEY_ID}" > ~/.gradle/gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> ~/.gradle/gradle.properties
          echo "signing.secretKeyRingFile=~/secring.kbx" >> ~/.gradle/gradle.properties
    - name: Publish to Nexus Repository
      shell: bash
      env:
        OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
        OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
      run: ./gradlew clean publish
  #     uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
  #     env:
  #       OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  #       OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  #     with:
  #       arguments: clean publish